# Training & eval numerical parameters
train_timesteps: 
train_episodes: 100
eval_freq: 100
render_freq: 50
n_eval_episodes: 10

# Seed
seed: 1234

# Parallelization
n_envs: 4

# Metrics
metrics:
  # Values
- MetricS_On_Learn
- Metric_Total_Reward
- Metric_Reward 
- Metric_Critic_Value_Unnormalized
# Performance
- Metric_Time_Count
- Metric_Performances
  # Other
- Metric_Epsilon
- Metric_Count_Episodes
- Metric_Action_Frequencies

# Logging
loggers:
# - ConsoleLogger 
# - TensorboardLogger 
# - WandbLogger 
# - DumpLogger

# Log & save directories
log_path: "logs"
log_path_tb: "logs/tensorboard"
models_path: "models"
best_model_path: "models/best_model"
final_model_path: "models/final_model"

# Loading 
checkpoint: "models/best_model"
checkpoint_criteria : "time"

# Name of the project
project_name : "RLProject"