create_algo_fn_string: rlearn.agents.ac:AC
algo_name: AC

algo_config:
  # Hyperparameters
  gamma : 0.99
  lam : 0.95
  learning_rate_actor : 0.001
  learning_rate_critic : 0.001
  n_step : 12

  # Learning
  reward_scaler : 100
  update_method : soft
  tau : 0.999
  target_update_interval : 10000
  gradient_clipping : 10
  train_freq_episode : 1
  gradient_steps_critic : 10
  gradient_steps_policy : 10
  batch_size : 64

  # Exploration
  learning_starts : 1000
  exploration_timesteps : 10000
  exploration_initial : 1
  exploration_final : 0.03

  # AC specific
  # compute_gain_method is among :
    # - "total_reward"
    # - "total_future_reward"
    # - "total_reward_minus_MC_mean"
    # - "total_reward_minus_leaky_mean"
    # - "total_future_reward_minus_state_value"
    # - "state_value"
    # - "state_value_centered"
    # - "GAE"
    # - "action_value"
    # - "action_value_centered"
    # - total_future_reward_minus_action_value
  compute_gain_method : GAE
  num_episodes : 10