create_algo_fn_string: rlearn.agents.dqn:DQN
algo_name: DQN

algo_config:
  #Hyper-parameters
  gamma : 0.99
  sample_size : 256
  learning_rate : 0.001

  # Learning
  reward_scaler : 10
  update_method : soft
  tau : 0.999
  target_update_interval : 10000
  clipping : null
  train_freq : 1
  gradients_steps : 10
  learning_starts : 1000

  # Exploration
  exploration_starts : 1000
  exploration_timesteps : 10000
  exploration_initial : 1
  exploration_final : 0.03

  # DQN specific
  n_step : 5
  buffer_size : 100000
  algorithm_method : Q-Learning  